fix: passing options when using @IsDateString()
typestack/class-validator pull request #1097
Opened 2021-05-26 12:29 UTC by hakimio

## Description

`@IsDateString({strict: true})` doesn't work because options are not passed to the validator.

### Fixes

Fixes #1061

2022-08-16 06:43 UTC, braaar requested changes

2022-08-16 06:43 UTC, braaar commented on src/decorator/string/IsDateString.ts
> +        validate: (value, args): boolean => isDateString(value, args.constraints[0]),
This should work and reads better, no?

```suggestion
        validate: (value, args): boolean => isDateString(value, options),
```

2022-08-16 06:43 UTC, braaar commented
Would you care to rebase/merge this to get rid of merge conflicts and irrelevant changes?

2022-08-16 07:01 UTC, closed without merging

2022-08-16 17:53 UTC, GCastilho commented
Any reason any it was closed?

2022-08-17 07:07 UTC, braaar commented
I would assume @hakimio is going to make a fresh PR instead of fixing this one. It's a bit cleaner that way, and it makes it easier to pass the [unnecessarily strict commit message check](https://github.com/typestack/class-validator/issues/1524)

2022-08-17 07:29 UTC, hakimio commented
PR #1720