feat: `validateIf` for validation options
typestack/class-validator pull request #1579
Opened 2022-03-11 14:09 UTC by aoi-umi

## Description

Add `validateIf` for validation options.
If you want to validate that condition by object, you can use `validation validateIf`.

`ValidateIf` will skip all other decorators, `validation validateIf` only effect the decorator that use this option

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

## Fixes
references https://github.com/typestack/class-validator/issues/1455

2022-03-28 17:20 UTC, Franco1312 submitted a review, later dismissed

2022-12-05 07:38 UTC, braaar commented
I think I prefer the `skip` or `skipIf` name for this option. I think `validateIf` is a bit confusing, since you can get it mixed up with the `ValidateIf` decorator.

2022-12-05 07:38 UTC, braaar commented
Handy feature, though!

2023-12-15 04:54 UTC, braaar reviewed
I think this is a good proposal, but I think the function should be normalized to match the predicate function used in `ValidateIf`. 

This is how I see it being the most useful:
```ts
@Max(5, { validateIf: (o) => Boolean(o.someOtherProperty) })
```

2023-12-15 05:15 UTC, braaar commented
See [my recent comment](https://github.com/typestack/class-validator/issues/1721#issuecomment-1857290706) in #1721

2024-01-15 07:06 UTC, braaar requested changes
As discussed in #1721, I think this decorator should have the same signature as `ValidateIf`. 

The signature `(value: any, validationArguments: ValidationArguments) => boolean;` makes it unnecessarily cumbersome to do simple stuff like: 
`@IsUUID({ validateIf: o => o.type === "something" })`

2024-01-24 13:02 UTC, aoi-umi commented
updated @braaar

2024-02-26 06:57 UTC, kevit-kelvin-mandlik commented
@braaar Please merge this feature I am waiting for so long...

2024-03-14 05:29 UTC, kevit-kelvin-mandlik commented
@braaar @aoi-umi  What are you guys waiting upon this? Can we please move forward with this?

2024-03-14 07:24 UTC, aoi-umi commented
> @braaar @aoi-umi What are you guys waiting upon this? Can we please move forward with this?

haha, i don't know either

2024-03-19 07:51 UTC, braaar commented
We are discussing this feature internally right now. Hold on just a little longer, @kevit-kelvin-mandlik and @aoi-umi

2024-04-24 13:10 UTC, kevit-kelvin-mandlik commented
@braaar Are we good to go on this??

2024-05-16 05:36 UTC, yasaichi commented
Any updates on this PR? I've been looking forward to using this feature for a quite long time!

2024-09-06 05:31 UTC, braaar commented
Hi again. Could I ask that you rewrite the docs and tests so that they more clearly illustrate the usefulness of this validation option? Personally I find the example in this PR a bit hard to parse. What does this actually mean in practice, you know?

```js
      validateIf: (obj: MyClass, value) => {
        return !obj.someOtherProperty || obj.someOtherProperty === 'min';
      },
```

I feel like that makes a poor case for this validation option. Adding a new feature should make people go "Nice! I like this!" rather than "Huh?"

2024-12-18 10:06 UTC, kelvinmandlik commented
@aoi-umi @braaar Can we please please move forward with this it's been so long for one small feature.

2025-01-20 05:43 UTC, braaar approved these changes, later dismissed
Let's ship this!

2025-01-20 06:43 UTC, braaar commented
I just noticed that codecov is picking up a line that is untested. Could you see to this, @aoi-umi?

2025-01-20 14:12 UTC, aoi-umi commented
> I just noticed that codecov is picking up a line that is untested. Could you see to this, @aoi-umi? 

haha, i almost forget this, the case `'should validate none'` should cover
it seems cause by source map
![image](https://github.com/user-attachments/assets/40a4c068-e464-4a9a-9244-1acb5bb54443)
![image](https://github.com/user-attachments/assets/595975f4-ce3d-46fa-8e7d-ff365b58082b)

2025-02-07 10:00 UTC, Magdan4ik commented
Hello, any updates or blockers? Been waiting for this feature!

2025-02-07 12:57 UTC, aoi-umi commented
@braaar please check

2025-02-18 11:21 UTC, MaxKoldun commented
@braaar Please merge this feature. I need it for my project.

2025-03-04 08:20 UTC, braaar commented
@aoi-umi check the latest CI / Linters action. The codecov is still not happy with the sourceMap change. Could you try refactoring the code in some way (perhaps inverting or re-ordering some if-statements) to see if that makes codecov happy?

2025-03-04 08:56 UTC, aoi-umi commented
sorry i forget to run the lint, it is ok now? @braaar

2025-03-04 08:59 UTC, braaar commented
Thanks. I'm still hesitant to merge due to the codecov problem. I'm not a test coverage hawk, I'm just worried that it might be catching something we aren't catching.

2026-02-25 07:40 UTC, braaar commented
I think it's time.

2026-02-25 07:51 UTC, braaar approved these changes

2026-02-25 07:52 UTC, merged