feat: @IsTaxID validator
typestack/class-validator pull request #1626
Opened 2022-04-21 23:45 UTC by kpkmw

## Description

@IsTaxID validator implemented.

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

<!-- fixes #[issue number], fixes #[issue number]

2022-07-29 12:12 UTC, Clashsoft requested changes

2022-07-29 12:12 UTC, Clashsoft commented on src/decorator/string/IsTaxID.ts
> + * Checks if the string is a credit card.
credit card → tax ID

2022-07-29 12:12 UTC, Clashsoft commented on src/decorator/string/IsTaxID.ts
> + * Checks if the string is a credit card.
credit card → tax ID

2022-11-20 18:35 UTC, NoNameProvided commented
Hey, thanks for opening the PR, please rebase or cherry-pick this to the latest `develop`.

2022-12-03 09:47 UTC, NoNameProvided commented
Superset by https://github.com/typestack/class-validator/pull/1822

2022-12-03 09:47 UTC, closed without merging