WIP fix: Fixed an error in the structure of the nestedValidation error messages.
typestack/class-validator pull request #673
Opened 2020-08-05 02:27 UTC by ytetsuro

## Description

When the property where the NestedValidation rule is defined contains a class other than Validation rules, it is in the children of ValidationError.

In other words, it will look like the following structure.

Input.ts

```typescript
class Input {
  @NestedValidation();
  hey: any;
}

const a = new Input();
a.hey = '';
```

error structure

```json
[
  {
    "children": [
      {
        "constraints": {
          "nestedValidation": "nested property hey must be either object or array"
        },
        "property": "hey",
        "target": "[Function Input]",
        "value": ""
      }
    ],
    "property": "hey",
    "target": {
      "hey": ""
    },
    "value": ""
  }
]
```

I think this is an error.
In the above example, since it's an error in the `hey` property, I think there should be `constraints` one level up, and that's why I fixed it.

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

fixes #[issue number], fixes #[issue number]

2020-08-06 12:02 UTC, KiziKr commented
Hello, I have exactly the same problem.

When i do that

```ts
@InputType()
export class SubCategoryContentInput {
    @Field()
    @Matches(/^[a-zA-Z]{3,25}$/)
    value: string;

    @Field(type => Language)
    lang: Language;
}

@InputType()
export class SubCategoryInput {

    @Field(type => MainCategory)
    public mainCategory: MainCategory;

    @ValidateNested()
    @Field(type => SubCategoryContentInput)
    public content: SubCategoryContentInput;
}
```

I get this error

```ts
"validationErrors": [
            {
              "target": {
                "mainCategory": "announcement",
                "content": {
                  "value": "test",
                  "lang": "fr"
                }
              },
              "value": {
                "value": "test",
                "lang": "fr"
              },
              "property": "content",
              "children": [
                {
                  "value": {
                    "value": "test",
                    "lang": "fr"
                  },
                  "property": "content",
                  "constraints": {
                    "nestedValidation": "nested property content must be either object or array"
                  }
                }
              ]
            }
```

And when I wanna make a table like this

```ts
    @ValidateNested()
    @Field(type => [SubCategoryContentInput])
    public content: SubCategoryContentInput[];
```

I get this error


```ts
"message": "Argument Validation Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSubCategory"
      ],
      "extensions": {
        "code": "ARGUMENT_VALIDATION_ERROR",
        "exception": {
          "validationErrors": {},
```

Sorry for my bad English, it's not my language.

2020-08-07 19:33 UTC, NoNameProvided requested changes
Please add tests for the test case defined in #679 (Testing valid behavior for both with primitive value and with an invalid class instance.)

2020-08-07 19:37 UTC, NoNameProvided commented
Hi! Thanks for your contribution! As I mentioned in the code review please add tests for the example in the linked issue. Something like:

```ts
// not valid test just guideance
expect(validationErrors[0].children[1].constraints).toHaveProperty('isString');
expect(validationErrors[1].constraints).toHaveProperty('nestedValidation');
```

2020-08-09 14:48 UTC, ytetsuro commented
@NoNameProvided

Thanks for the comment.
Fixed.

And, fixes a problem where the stopAtFirstError option would cause two errors, when set nestedValidation.
Presumably, blame is this fix.

2020-08-17 10:35 UTC, ytetsuro commented
@NoNameProvided

Sorry to take you out of your busy schedule, but I hope you'll take a re-review at it when you have time.

2021-03-23 07:16 UTC, ytetsuro commented
@NoNameProvided

Sorry to take you out of your busy schedule, but I hope you'll take a re-review at it when you have time.

2022-11-20 11:48 UTC, NoNameProvided approved these changes

2022-11-20 11:50 UTC, merged

2022-11-20 11:51 UTC, NoNameProvided commented
Thanks @ytetsuro!

2022-11-22 04:02 UTC, ytetsuro commented
Thanks merged!